package com.genshincalc.core.showcase

import com.genshincalc.core.calc.BaseStats
import com.genshincalc.core.calc.StatSheet
import com.genshincalc.core.model.ArtifactBuild
import com.genshincalc.core.model.ArtifactMode
import com.genshincalc.core.model.ArtifactPiece
import com.genshincalc.core.model.ArtifactSlot
import com.genshincalc.core.model.Element
import com.genshincalc.core.model.GameDataSet
import com.genshincalc.core.model.ManualStats
import com.genshincalc.core.model.MemberBuild
import com.genshincalc.core.model.Stat
import com.genshincalc.core.model.TalentLevels
import com.genshincalc.core.model.WeaponBuild
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlin.math.abs
import kotlin.math.max

/** Game ids used by the in-game Character Showcase, mapped to this app's ids (generated by tools/datagen). */
@Serializable
data class ShowcaseIds(
    /** Avatar id (travelers: "avatarId-skillDepotId") -> character. */
    val characters: Map<String, CharacterIds> = emptyMap(),
    /** Weapon item id -> weapon id. */
    val weapons: Map<String, String> = emptyMap(),
    /** Artifact set id -> set id. */
    val sets: Map<String, String> = emptyMap(),
) {
    /** [skills]: Normal Attack, Elemental Skill and Elemental Burst skill ids. */
    @Serializable
    data class CharacterIds(val id: String, val skills: List<Long>)

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        @Volatile
        private var cached: ShowcaseIds? = null

        fun load(): ShowcaseIds = cached ?: synchronized(this) {
            cached ?: (ShowcaseIds::class.java.getResourceAsStream("/gamedata/showcase.json") ?: error("Missing resource gamedata/showcase.json"))
                .use { json.decodeFromString(serializer(), it.readBytes().decodeToString()) }
                .also { cached = it }
        }
    }
}

data class ShowcasePlayer(val nickname: String?, val level: Int?, val worldLevel: Int?, val signature: String?)

/** One showcased character. */
data class ShowcaseCharacter(
    /** Level, constellation, talents, weapon and the five artifacts (individual pieces). */
    val build: MemberBuild,
    /** The character's in-game attribute screen (percent stats as fractions). */
    val gameStats: ManualStats,
    val warnings: List<String> = emptyList(),
)

data class Showcase(
    val uid: String?,
    val player: ShowcasePlayer,
    /** In showcase order. */
    val characters: List<ShowcaseCharacter>,
    /** Number of showcased characters this app doesn't know yet (newer than its data). */
    val unknownCharacters: Int,
    /** The player turned off "Show Character Details" (or the showcase is empty). */
    val detailsHidden: Boolean,
)

/** A difference between the in-game attribute screen and the calculated one. */
data class StatDifference(val label: String, val game: Double, val calculated: Double, val percent: Boolean)

/**
 * Reads the Character Showcase of a player as returned by the Enka.Network API
 * (`https://enka.network/api/uid/{uid}/`).
 */
object ShowcaseParser {
    private val PROPS = mapOf(
        "FIGHT_PROP_HP" to Stat.HP, "FIGHT_PROP_HP_PERCENT" to Stat.HP_PCT,
        "FIGHT_PROP_ATTACK" to Stat.ATK, "FIGHT_PROP_ATTACK_PERCENT" to Stat.ATK_PCT,
        "FIGHT_PROP_DEFENSE" to Stat.DEF, "FIGHT_PROP_DEFENSE_PERCENT" to Stat.DEF_PCT,
        "FIGHT_PROP_ELEMENT_MASTERY" to Stat.EM, "FIGHT_PROP_CHARGE_EFFICIENCY" to Stat.ER,
        "FIGHT_PROP_CRITICAL" to Stat.CRIT_RATE, "FIGHT_PROP_CRITICAL_HURT" to Stat.CRIT_DMG,
        "FIGHT_PROP_HEAL_ADD" to Stat.HEALING_BONUS, "FIGHT_PROP_PHYSICAL_ADD_HURT" to Stat.PHYSICAL_DMG,
        "FIGHT_PROP_FIRE_ADD_HURT" to Stat.PYRO_DMG, "FIGHT_PROP_WATER_ADD_HURT" to Stat.HYDRO_DMG,
        "FIGHT_PROP_WIND_ADD_HURT" to Stat.ANEMO_DMG, "FIGHT_PROP_ELEC_ADD_HURT" to Stat.ELECTRO_DMG,
        "FIGHT_PROP_GRASS_ADD_HURT" to Stat.DENDRO_DMG, "FIGHT_PROP_ICE_ADD_HURT" to Stat.CRYO_DMG,
        "FIGHT_PROP_ROCK_ADD_HURT" to Stat.GEO_DMG,
    )
    private val SLOTS = mapOf(
        "EQUIP_BRACER" to ArtifactSlot.FLOWER, "EQUIP_NECKLACE" to ArtifactSlot.PLUME, "EQUIP_SHOES" to ArtifactSlot.SANDS,
        "EQUIP_RING" to ArtifactSlot.GOBLET, "EQUIP_DRESS" to ArtifactSlot.CIRCLET,
    )
    /** fightPropMap keys of the elemental DMG bonuses. */
    private val DMG_PROPS = mapOf(
        "30" to Element.PHYSICAL, "40" to Element.PYRO, "41" to Element.ELECTRO, "42" to Element.HYDRO,
        "43" to Element.DENDRO, "44" to Element.ANEMO, "45" to Element.GEO, "46" to Element.CRYO,
    )
    private val RELIC_ICON = Regex("""UI_RelicIcon_(\d+)_\d""")
    private val TRAVELERS = setOf("10000005", "10000007")

    fun parse(text: String, data: GameDataSet, ids: ShowcaseIds, newPieceId: () -> String): Showcase {
        val root = runCatching { Json.parseToJsonElement(text) as JsonObject }
            .getOrElse { throw ShowcaseFormatException("Unexpected response from the showcase service") }
        val info = root.obj("playerInfo")
        val player = ShowcasePlayer(
            nickname = info?.str("nickname"),
            level = info?.int("level"),
            worldLevel = info?.int("worldLevel"),
            signature = info?.str("signature"),
        )
        val avatars = root["avatarInfoList"] as? JsonArray
        if (avatars.isNullOrEmpty()) {
            return Showcase(root.str("uid"), player, emptyList(), 0, detailsHidden = true)
        }
        // Showcase order (avatarInfoList normally already follows it).
        val order = (info?.get("showAvatarInfoList") as? JsonArray).orEmpty()
            .mapNotNull { (it as? JsonObject)?.str("avatarId") }
        val sorted = avatars.mapNotNull { it as? JsonObject }
            .sortedBy { a -> order.indexOf(a.str("avatarId")).let { if (it < 0) Int.MAX_VALUE else it } }
        var unknown = 0
        val characters = sorted.mapNotNull { a ->
            parseCharacter(a, data, ids, newPieceId).also { if (it == null) unknown++ }
        }
        return Showcase(root.str("uid"), player, characters, unknown, detailsHidden = false)
    }

    private fun parseCharacter(a: JsonObject, data: GameDataSet, ids: ShowcaseIds, newPieceId: () -> String): ShowcaseCharacter? {
        val avatarId = a.str("avatarId") ?: return null
        val key = if (avatarId in TRAVELERS) "$avatarId-${a.str("skillDepotId")}" else avatarId
        val known = ids.characters[key] ?: return null
        val character = data.characterOrNull(known.id) ?: return null
        val warnings = mutableListOf<String>()

        val props = a.obj("propMap")
        val level = (props?.obj("4001")?.let { it.int("val") ?: it.int("ival") } ?: 1).coerceIn(1, BaseStats.MAX_CHARACTER_LEVEL)
        val ascension = props?.obj("1002")?.let { it.int("val") ?: it.int("ival") } ?: 0
        val constellation = ((a["talentIdList"] as? JsonArray)?.size ?: 0).coerceIn(0, 6)
        val skills = a.obj("skillLevelMap")
        fun talent(i: Int) = (known.skills.getOrNull(i)?.let { skills?.int(it.toString()) } ?: 1).coerceIn(1, 10)

        var weapon: WeaponBuild? = null
        val pieces = mutableMapOf<ArtifactSlot, ArtifactPiece>()
        for (item in (a["equipList"] as? JsonArray).orEmpty().mapNotNull { it as? JsonObject }) {
            val flat = item.obj("flat")
            val w = item.obj("weapon")
            val r = item.obj("reliquary")
            when {
                w != null -> {
                    val id = ids.weapons[item.str("itemId")]?.takeIf { data.weaponOrNull(it) != null }
                    if (id == null) {
                        warnings += "Weapon not in this app's data yet (a default one is used)"
                        continue
                    }
                    val wLevel = (w.int("level") ?: 1).coerceIn(1, data.weapon(id).maxLevel)
                    val refinement = ((w.obj("affixMap")?.values?.firstOrNull() as? JsonPrimitive)?.content?.toIntOrNull() ?: 0) + 1
                    weapon = WeaponBuild(id, wLevel, ascended(wLevel, w.int("promoteLevel") ?: 0), refinement.coerceIn(1, 5))
                }
                r != null && flat != null -> {
                    val piece = parseArtifact(flat, r, data, ids, newPieceId(), warnings) ?: continue
                    pieces[piece.slot] = piece
                }
            }
        }
        if (weapon == null) weapon = com.genshincalc.core.Defaults.build(data, character.id).weapon

        val build = MemberBuild(
            characterId = character.id,
            level = level,
            ascended = ascended(level, ascension),
            constellation = constellation,
            talents = TalentLevels(talent(0), talent(1), talent(2)),
            weapon = weapon,
            artifacts = ArtifactBuild(mode = ArtifactMode.PIECES, pieces = pieces),
            manualStats = gameStats(a.obj("fightPropMap")),
        )
        return ShowcaseCharacter(build, build.manualStats, warnings)
    }

    private fun parseArtifact(
        flat: JsonObject, r: JsonObject, data: GameDataSet, ids: ShowcaseIds, id: String, warnings: MutableList<String>,
    ): ArtifactPiece? {
        val slot = SLOTS[flat.str("equipType")] ?: return null
        val setNumber = flat.str("icon")?.let { RELIC_ICON.find(it)?.groupValues?.get(1) }
        val setId = setNumber?.let { ids.sets[it] }?.takeIf { data.artifactSetOrNull(it) != null }
        if (setId == null) warnings += "Artifact set of the ${slot.display.lowercase()} not in this app's data yet"
        val main = flat.obj("reliquaryMainstat")
        val mainStat = main?.str("mainPropId")?.let { PROPS[it] }
        val substats = (flat["reliquarySubstats"] as? JsonArray).orEmpty().mapNotNull { it as? JsonObject }.mapNotNull { s ->
            val stat = s.str("appendPropId")?.let { PROPS[it] } ?: return@mapNotNull null
            val value = s.double("statValue") ?: s.double("propValue") ?: return@mapNotNull null
            stat to if (stat.percent) value / 100 else value
        }.toMap()
        val piece = ArtifactPiece(
            id = id,
            setId = setId,
            slot = slot,
            mainStat = mainStat ?: slot.mainStats.first(),
            rarity = flat.int("rankLevel") ?: 5,
            level = ((r.int("level") ?: 1) - 1).coerceAtLeast(0),
            substats = substats,
        ).normalized()
        // The game's main stat value is a check on rarity/level.
        val shown = main?.let { it.double("statValue") ?: it.double("propValue") }
        if (shown != null) {
            val expected = BaseStats.pieceMain(data, piece) * if (piece.mainStat.percent) 100 else 1
            if (abs(expected - shown) > max(1.0, shown * 0.01)) warnings += "${slot.display} main stat differs from the game"
        }
        return piece
    }

    /** True when [level] is an ascension cap the character/weapon has already passed (e.g. 80/90). */
    private fun ascended(level: Int, promoteLevel: Int): Boolean =
        promoteLevel >= BaseStats.ascensionFor(level, true)

    private fun gameStats(f: JsonObject?): ManualStats {
        if (f == null) return ManualStats()
        fun v(key: String) = f.double(key) ?: 0.0
        return ManualStats(
            baseHp = v("1"), baseAtk = v("4"), baseDef = v("7"),
            hp = v("2000"), atk = v("2001"), def = v("2002"),
            em = v("28"), critRate = v("20"), critDmg = v("22"), er = v("23"),
            healingBonus = v("26"),
            dmgBonus = DMG_PROPS.mapNotNull { (k, e) -> f.double(k)?.takeIf { it != 0.0 }?.let { e to it } }.toMap(),
        )
    }

    /**
     * Compares the in-game attribute screen with the calculated one; differences above rounding are returned
     * (an empty list means the calculation reproduces the game).
     */
    fun compare(game: ManualStats, calculated: StatSheet, element: Element): List<StatDifference> {
        val rows = listOf(
            Triple("Max HP", game.hp, calculated.hp), Triple("ATK", game.atk, calculated.atk),
            Triple("DEF", game.def, calculated.def), Triple("Elemental Mastery", game.em, calculated.em),
        ).map { (l, g, c) -> StatDifference(l, g, c, false) } + listOf(
            Triple("CRIT Rate", game.critRate, calculated.critRate), Triple("CRIT DMG", game.critDmg, calculated.critDmg),
            Triple("Energy Recharge", game.er, calculated.er),
            Triple("${element.display} DMG Bonus", game.dmgBonus[element] ?: 0.0, calculated.dmgBonus(element)),
        ).map { (l, g, c) -> StatDifference(l, g, c, true) }
        return rows.filter { d ->
            if (d.percent) abs(d.game - d.calculated) > 0.0015 else abs(d.game - d.calculated) > max(1.5, d.game * 0.002)
        }
    }

    private fun JsonObject.obj(key: String) = this[key] as? JsonObject
    private fun JsonObject.str(key: String) = (this[key] as? JsonPrimitive)?.content
    private fun JsonObject.int(key: String) = str(key)?.toDoubleOrNull()?.toInt()
    private fun JsonObject.double(key: String) = str(key)?.toDoubleOrNull()
}

class ShowcaseFormatException(message: String) : Exception(message)
