DECLINE_CODES = [
    # RECOVERABLE
    {
        "code": "INSUFFICIENT_FUNDS",
        "category": "RECOVERABLE",
        "description": "Card declined due to insufficient funds",
        "recoverable": True,
        "default_retry_strategy": "payday",
    },
    {
        "code": "EXPIRED_CARD",
        "category": "RECOVERABLE",
        "description": "Card has expired",
        "recoverable": True,
        "default_retry_strategy": "prompt_customer",
    },
    {
        "code": "CARD_LIMIT_EXCEEDED",
        "category": "RECOVERABLE",
        "description": "Transaction exceeds card limit",
        "recoverable": True,
        "default_retry_strategy": "scheduled",
    },
    # HARD_DECLINE
    {
        "code": "STOLEN_CARD",
        "category": "HARD_DECLINE",
        "description": "Card reported stolen",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    {
        "code": "ACCOUNT_CLOSED",
        "category": "HARD_DECLINE",
        "description": "Bank account is closed",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    {
        "code": "INVALID_CARD",
        "category": "HARD_DECLINE",
        "description": "Card number or details are invalid",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    {
        "code": "DO_NOT_HONOR",
        "category": "HARD_DECLINE",
        "description": "Bank declined without specific reason",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    # TECHNICAL
    {
        "code": "GATEWAY_TIMEOUT",
        "category": "TECHNICAL",
        "description": "Payment gateway timed out",
        "recoverable": True,
        "default_retry_strategy": "immediate",
    },
    {
        "code": "API_ERROR",
        "category": "TECHNICAL",
        "description": "API error from payment gateway",
        "recoverable": True,
        "default_retry_strategy": "immediate",
    },
    {
        "code": "NETWORK_ERROR",
        "category": "TECHNICAL",
        "description": "Network connectivity error",
        "recoverable": True,
        "default_retry_strategy": "immediate",
    },
    {
        "code": "PROCESSING_ERROR",
        "category": "TECHNICAL",
        "description": "Generic processing error at gateway",
        "recoverable": True,
        "default_retry_strategy": "immediate",
    },
    # FRAUD_RISK
    {
        "code": "BANK_FRAUD_BLOCK",
        "category": "FRAUD_RISK",
        "description": "Bank flagged transaction as potential fraud",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    {
        "code": "3DS_FAILED",
        "category": "FRAUD_RISK",
        "description": "3D Secure authentication failed",
        "recoverable": True,
        "default_retry_strategy": "prompt_customer",
    },
    {
        "code": "RISK_THRESHOLD",
        "category": "FRAUD_RISK",
        "description": "Transaction exceeded risk threshold",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
    # CUSTOMER_ACTION
    {
        "code": "AUTHENTICATION_REQUIRED",
        "category": "CUSTOMER_ACTION",
        "description": "Additional authentication required",
        "recoverable": True,
        "default_retry_strategy": "prompt_customer",
    },
    {
        "code": "CARD_NOT_SUPPORTED",
        "category": "CUSTOMER_ACTION",
        "description": "Card type not supported for this transaction",
        "recoverable": True,
        "default_retry_strategy": "prompt_customer",
    },
    # UNKNOWN
    {
        "code": "UNKNOWN",
        "category": "UNKNOWN",
        "description": "Unrecognized decline code — flagged for manual mapping",
        "recoverable": False,
        "default_retry_strategy": "none",
    },
]

GATEWAY_CODE_MAPPINGS = [
    # Stripe-style codes (~15)
    {"gateway": "stripe", "gateway_code": "insufficient_funds", "unified_code": "INSUFFICIENT_FUNDS"},
    {"gateway": "stripe", "gateway_code": "expired_card", "unified_code": "EXPIRED_CARD"},
    {"gateway": "stripe", "gateway_code": "card_velocity_exceeded", "unified_code": "CARD_LIMIT_EXCEEDED"},
    {"gateway": "stripe", "gateway_code": "stolen_card", "unified_code": "STOLEN_CARD"},
    {"gateway": "stripe", "gateway_code": "account_closed", "unified_code": "ACCOUNT_CLOSED"},
    {"gateway": "stripe", "gateway_code": "invalid_number", "unified_code": "INVALID_CARD"},
    {"gateway": "stripe", "gateway_code": "do_not_honor", "unified_code": "DO_NOT_HONOR"},
    {"gateway": "stripe", "gateway_code": "processing_error", "unified_code": "PROCESSING_ERROR"},
    {"gateway": "stripe", "gateway_code": "fraudulent", "unified_code": "BANK_FRAUD_BLOCK"},
    {"gateway": "stripe", "gateway_code": "authentication_required", "unified_code": "AUTHENTICATION_REQUIRED"},
    {"gateway": "stripe", "gateway_code": "card_not_supported", "unified_code": "CARD_NOT_SUPPORTED"},
    {"gateway": "stripe", "gateway_code": "3d_secure_failed", "unified_code": "3DS_FAILED"},
    {"gateway": "stripe", "gateway_code": "gateway_timeout", "unified_code": "GATEWAY_TIMEOUT"},
    {"gateway": "stripe", "gateway_code": "api_error", "unified_code": "API_ERROR"},
    {"gateway": "stripe", "gateway_code": "network_error", "unified_code": "NETWORK_ERROR"},
    # Mock gateway mirrors stripe codes
    {"gateway": "mock", "gateway_code": "insufficient_funds", "unified_code": "INSUFFICIENT_FUNDS"},
    {"gateway": "mock", "gateway_code": "expired_card", "unified_code": "EXPIRED_CARD"},
    {"gateway": "mock", "gateway_code": "card_velocity_exceeded", "unified_code": "CARD_LIMIT_EXCEEDED"},
    {"gateway": "mock", "gateway_code": "stolen_card", "unified_code": "STOLEN_CARD"},
    {"gateway": "mock", "gateway_code": "account_closed", "unified_code": "ACCOUNT_CLOSED"},
    {"gateway": "mock", "gateway_code": "invalid_number", "unified_code": "INVALID_CARD"},
    {"gateway": "mock", "gateway_code": "do_not_honor", "unified_code": "DO_NOT_HONOR"},
    {"gateway": "mock", "gateway_code": "processing_error", "unified_code": "PROCESSING_ERROR"},
    {"gateway": "mock", "gateway_code": "fraudulent", "unified_code": "BANK_FRAUD_BLOCK"},
    {"gateway": "mock", "gateway_code": "authentication_required", "unified_code": "AUTHENTICATION_REQUIRED"},
    {"gateway": "mock", "gateway_code": "card_not_supported", "unified_code": "CARD_NOT_SUPPORTED"},
    {"gateway": "mock", "gateway_code": "3d_secure_failed", "unified_code": "3DS_FAILED"},
    {"gateway": "mock", "gateway_code": "gateway_timeout", "unified_code": "GATEWAY_TIMEOUT"},
    {"gateway": "mock", "gateway_code": "api_error", "unified_code": "API_ERROR"},
    {"gateway": "mock", "gateway_code": "network_error", "unified_code": "NETWORK_ERROR"},
    # Razorpay-style codes (~10)
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/insufficient_funds", "unified_code": "INSUFFICIENT_FUNDS"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/card_expired", "unified_code": "EXPIRED_CARD"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/card_limit_exceeded", "unified_code": "CARD_LIMIT_EXCEEDED"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/invalid_card", "unified_code": "INVALID_CARD"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/do_not_honour", "unified_code": "DO_NOT_HONOR"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/stolen_card", "unified_code": "STOLEN_CARD"},
    {"gateway": "razorpay", "gateway_code": "GATEWAY_ERROR/processing_error", "unified_code": "PROCESSING_ERROR"},
    {"gateway": "razorpay", "gateway_code": "GATEWAY_ERROR/gateway_timeout", "unified_code": "GATEWAY_TIMEOUT"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/authentication_required", "unified_code": "AUTHENTICATION_REQUIRED"},
    {"gateway": "razorpay", "gateway_code": "BAD_REQUEST_ERROR/fraud_detected", "unified_code": "BANK_FRAUD_BLOCK"},
]
